# Generated by Django 2.1 on 2019-02-03 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20190126_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankentbl',
            name='REQUESTDATE',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
