# Generated by Django 2.1 on 2019-02-03 10:18

from django.db import migrations, models
import hello.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20190203_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankentbl',
            name='ANKENID',
            field=models.CharField(default=hello.models.get_next, max_length=10),
        ),
    ]
